import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box, Text, Button } from "@chakra-ui/react"
import { Input } from "@chakra-ui/react"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w={'200px'} h={"200px"} bg={'brand.darkGreen'}>
        <Text>
          Ozod
        </Text>
        <Button variant={'outlined'} size={'sx'}>
          hha
        </Button>
        <Input placeholder={'hello'} variant={'outlined'}/>
      </Box>
    </div>
  )
}
